name: 'Test'
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 🛒
              uses: actions/checkout@v4

            - name: Setup bun 🔧
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies 📦
              run: bun install

            - name: Run test units (with coverage reports) 🧪
              run: bun test --coverage
